/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Student;

import CourseCatalog.Course;
import CourseCatalog.CourseOffer;
import CourseCatalog.CourseSchedule;
import CourseCatalog.SeatAssignment;
import Platform.Platform;
import Student.Student;
import java.util.ArrayList;
import javax.lang.model.type.ErrorType;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15512
 */
public class MyCoursesScreen extends javax.swing.JPanel {

    /**
     * Creates new form RegisterCourse
     */
    private Platform platform;
    private Student student;
    private String term;
    private DefaultTableModel courseTableModel;
    private DefaultTableModel registeredTableModel;

    public MyCoursesScreen(Platform platform, Student s) {
        initComponents();
        this.setVisible(true);

        this.platform = platform;
        this.student = s;
        this.registeredTableModel = (DefaultTableModel) registeredTable.getModel();
        populateRegisteredCourse();
    }

    public void populateRegisteredCourse() {
        registeredTableModel.setRowCount(0);
        int totalPrice = 0;
        try {
            for (SeatAssignment sa : this.student.getTranscript().getSeatAssignmentsAllTerms()) {

                Course c = sa.getSeat().getCourseoffer().getCourse();
                Object[] row = new Object[6];

                row[0] = sa.getCourseload().getTerm();
                row[1] = c.getName();
                row[2] = c.getTopic();
                row[3] = sa.getSeat().getCourseoffer().getProfessor().getName();
                row[4] = c.getRegion();
                row[5] = c.getLanguage();
       
                registeredTableModel.addRow(row);
                totalPrice += c.getPrice();
            }
            tuition.setText(String.valueOf(totalPrice));
        } catch (Throwable e) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        registeredTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        payCourses = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tuition = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 51));

        registeredTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Term", "Name", "Topic", "Professor", "Region", "Language"
            }
        ));
        jScrollPane2.setViewportView(registeredTable);

        jLabel4.setText("My Courses");

        payCourses.setText("Pay for courses");
        payCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payCoursesActionPerformed(evt);
            }
        });

        jLabel6.setText("Total Tuition");

        tuition.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        tuition.setText("Price");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(tuition))
                    .addComponent(payCourses))
                .addGap(307, 307, 307))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel4)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tuition))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(payCourses)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void payCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payCoursesActionPerformed
        // TODO add your handling code here:
        if (!this.student.getTuitionPaidForAllCO()) {
            for (SeatAssignment sa: this.student.getCourseList()){
                if (!sa.getPaid()){
                    sa.setPaid(true);
                }
            }
            this.student.setTuitionPaidForAllCO(true);
            JOptionPane.showMessageDialog(null, "Tuition Paid!");
        } else {
            JOptionPane.showMessageDialog(null, "Tuition Already Paid!");
        }
    }//GEN-LAST:event_payCoursesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton payCourses;
    private javax.swing.JTable registeredTable;
    private javax.swing.JLabel tuition;
    // End of variables declaration//GEN-END:variables
}
