/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Student;

import CourseCatalog.Course;
import CourseCatalog.SeatAssignment;
import Platform.Platform;
import Student.Student;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 15512
 */
public class TranscriptScreen extends javax.swing.JPanel {

    /**
     * Creates new form TranscriptScreen
     */
    private Platform platform;
    private DefaultTableModel transcriptTableModel;
    private Student student;

    public TranscriptScreen(Platform platform, Student student) {
        initComponents();
        this.platform = platform;
        this.student = student;
        this.transcriptTableModel = (DefaultTableModel) transcriptTable.getModel();
        gradStatus.setText(this.student.getTranscript().getGraduationStatus());
        populateTranscript();
    }

    public void populateTranscript() {
        transcriptTableModel.setRowCount(0);
        for (SeatAssignment sa : this.student.getTranscript().getSeatAssignmentsAllTerms()) {
            Course c = sa.getSeat().getCourseoffer().getCourse();
            Object[] row = new Object[5];
            row[0] = sa.getCourseload().getTerm();
            row[1] = c;
            row[2] = sa.getSeat().getCourseoffer().getProfessor().getName();
            row[3] = sa;
            row[4] = sa.getGrade();
            
            transcriptTableModel.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        transcriptTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        registerRequest = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        gradStatus = new javax.swing.JLabel();
        rateBtn = new javax.swing.JButton();
        fieldRate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 255));

        transcriptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Term", "Course", "Professor", "Seat", "Grade"
            }
        ));
        jScrollPane1.setViewportView(transcriptTable);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Transcript");

        registerRequest.setText("Request for graduation");
        registerRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerRequestActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Graduation Status: ");

        gradStatus.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        gradStatus.setText("ss");

        rateBtn.setText("Rate Professor");
        rateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rateBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Rating: (1-5)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gradStatus))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(registerRequest, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rateBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(gradStatus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(registerRequest)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(fieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rateBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void registerRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerRequestActionPerformed
        // TODO add your handling code here:
        if (this.student.getTuitionPaidForAllCO()) {
            if (this.student.getRequested()) {
                JOptionPane.showMessageDialog(null, "Already requested for graduation");
            } else {
                this.student.setRequested(true);
                JOptionPane.showMessageDialog(null, "Requested for graduation");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Pay Tuition fee first!");
        }

    }//GEN-LAST:event_registerRequestActionPerformed

    private void rateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = transcriptTable.getSelectedRow();
        SeatAssignment sa = (SeatAssignment) transcriptTable.getValueAt(selectedRow, 3);
        
        //students can rate after they finish the course
        if (sa.getGrade().equals("Pass") || sa.getGrade().equals("Fail") ){
            sa.setProfessorRepGrading(Integer.valueOf(fieldRate.getText()));
            JOptionPane.showMessageDialog(null, "Rated professor");
        }else{
            JOptionPane.showMessageDialog(null, "Finish the course before rating");
        }
        
    }//GEN-LAST:event_rateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldRate;
    private javax.swing.JLabel gradStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton rateBtn;
    private javax.swing.JButton registerRequest;
    private javax.swing.JTable transcriptTable;
    // End of variables declaration//GEN-END:variables
}
